# Generated by Django 5.0.2 on 2024-09-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
